AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.6
Layout:
  Enabled: true
Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block
Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint:
  Enabled: true
Metrics/LineLength:
  Enabled: true
  Exclude:
    - "bin/**"
    - db/schema.rb
Naming:
  Enabled: true
Security:
  Enabled: true
Style:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
Style/NumericPredicate:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
